<?php

namespace Database\Seeders;

use App\Models\Company;
use Illuminate\Database\Seeder;

class CompanySeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $companies = collect([
            // ── Entertainment (1) ────────────────────────────────────────────────
            ['name' => 'Netflix', 'logo_url' => $this->getCompanyLogo('netflix.com'), 'category_id' => 1],
            ['name' => 'Spotify', 'logo_url' => $this->getCompanyLogo('spotify.com'), 'category_id' => 1],
            ['name' => 'Disney+', 'logo_url' => $this->getCompanyLogo('disneyplus.com'), 'category_id' => 1],
            ['name' => 'Hulu', 'logo_url' => $this->getCompanyLogo('hulu.com'), 'category_id' => 1],
            ['name' => 'HBO Max', 'logo_url' => $this->getCompanyLogo('max.com'), 'category_id' => 1],
            ['name' => 'Apple TV+', 'logo_url' => $this->getCompanyLogo('apple.com'), 'category_id' => 1],
            ['name' => 'YouTube Premium', 'logo_url' => $this->getCompanyLogo('youtube.com'), 'category_id' => 1],
            ['name' => 'Crunchyroll', 'logo_url' => $this->getCompanyLogo('crunchyroll.com'), 'category_id' => 1],
            ['name' => 'Paramount+', 'logo_url' => $this->getCompanyLogo('paramountplus.com'), 'category_id' => 1],
            ['name' => 'Peacock', 'logo_url' => $this->getCompanyLogo('peacocktv.com'), 'category_id' => 1],
            ['name' => 'Tidal', 'logo_url' => $this->getCompanyLogo('tidal.com'), 'category_id' => 1],
            ['name' => 'Amazon Prime Video', 'logo_url' => $this->getCompanyLogo('primevideo.com'), 'category_id' => 1],
            ['name' => 'Deezer', 'logo_url' => $this->getCompanyLogo('deezer.com'), 'category_id' => 1],
            ['name' => 'MUBI', 'logo_url' => $this->getCompanyLogo('mubi.com'), 'category_id' => 1],
            ['name' => 'Shudder', 'logo_url' => $this->getCompanyLogo('shudder.com'), 'category_id' => 1],
            ['name' => 'Discovery+', 'logo_url' => $this->getCompanyLogo('discoveryplus.com'), 'category_id' => 1],
            ['name' => 'BritBox', 'logo_url' => $this->getCompanyLogo('britbox.com'), 'category_id' => 1],
            ['name' => 'Acorn TV', 'logo_url' => $this->getCompanyLogo('acorn.tv'), 'category_id' => 1],
            ['name' => 'Funimation', 'logo_url' => $this->getCompanyLogo('funimation.com'), 'category_id' => 1],
            ['name' => 'CuriosityStream', 'logo_url' => $this->getCompanyLogo('curiositystream.com'), 'category_id' => 1],
            ['name' => 'Nebula', 'logo_url' => $this->getCompanyLogo('watchnebula.com'), 'category_id' => 1],
            ['name' => 'Dropout', 'logo_url' => $this->getCompanyLogo('dropout.tv'), 'category_id' => 1],
            ['name' => 'Starz', 'logo_url' => $this->getCompanyLogo('starz.com'), 'category_id' => 1],
            ['name' => 'Showtime', 'logo_url' => $this->getCompanyLogo('showtime.com'), 'category_id' => 1],
            ['name' => 'AMC+', 'logo_url' => $this->getCompanyLogo('amcplus.com'), 'category_id' => 1],
            ['name' => 'ESPN+', 'logo_url' => $this->getCompanyLogo('espn.com'), 'category_id' => 1],
            ['name' => 'DAZN', 'logo_url' => $this->getCompanyLogo('dazn.com'), 'category_id' => 1],
            ['name' => 'fuboTV', 'logo_url' => $this->getCompanyLogo('fubo.tv'), 'category_id' => 1],
            ['name' => 'Philo', 'logo_url' => $this->getCompanyLogo('philo.com'), 'category_id' => 1],
            ['name' => 'Sling TV', 'logo_url' => $this->getCompanyLogo('sling.com'), 'category_id' => 1],
            ['name' => 'Qobuz', 'logo_url' => $this->getCompanyLogo('qobuz.com'), 'category_id' => 1],
            ['name' => 'Pandora', 'logo_url' => $this->getCompanyLogo('pandora.com'), 'category_id' => 1],
            ['name' => 'SoundCloud', 'logo_url' => $this->getCompanyLogo('soundcloud.com'), 'category_id' => 1],
            ['name' => 'Audible', 'logo_url' => $this->getCompanyLogo('audible.com'), 'category_id' => 1],
            ['name' => 'Scribd', 'logo_url' => $this->getCompanyLogo('scribd.com'), 'category_id' => 1],
            ['name' => 'Blinkist', 'logo_url' => $this->getCompanyLogo('blinkist.com'), 'category_id' => 1],
            ['name' => 'Readly', 'logo_url' => $this->getCompanyLogo('readly.com'), 'category_id' => 1],
            ['name' => 'Plex', 'logo_url' => $this->getCompanyLogo('plex.tv'), 'category_id' => 1],
            ['name' => 'FloSports', 'logo_url' => $this->getCompanyLogo('flosports.tv'), 'category_id' => 1],
            ['name' => 'UFC Fight Pass', 'logo_url' => $this->getCompanyLogo('ufc.com'), 'category_id' => 1],
            ['name' => 'WWE Network', 'logo_url' => $this->getCompanyLogo('wwe.com'), 'category_id' => 1],
            ['name' => 'HIDIVE', 'logo_url' => $this->getCompanyLogo('hidive.com'), 'category_id' => 1],
            ['name' => 'Eros Now', 'logo_url' => $this->getCompanyLogo('erosnow.com'), 'category_id' => 1],
            ['name' => 'ZEE5', 'logo_url' => $this->getCompanyLogo('zee5.com'), 'category_id' => 1],
            ['name' => 'Canal+', 'logo_url' => $this->getCompanyLogo('canalplus.com'), 'category_id' => 1],

            // ── Productivity (2) ─────────────────────────────────────────────────
            ['name' => 'Notion', 'logo_url' => $this->getCompanyLogo('notion.so'), 'category_id' => 2],
            ['name' => 'ChatGPT Plus', 'logo_url' => $this->getCompanyLogo('openai.com'), 'category_id' => 2],
            ['name' => 'Claude Pro', 'logo_url' => $this->getCompanyLogo('anthropic.com'), 'category_id' => 2],
            ['name' => 'Figma', 'logo_url' => $this->getCompanyLogo('figma.com'), 'category_id' => 2],
            ['name' => 'Adobe Creative Cloud', 'logo_url' => $this->getCompanyLogo('adobe.com'), 'category_id' => 2],
            ['name' => 'Dropbox', 'logo_url' => $this->getCompanyLogo('dropbox.com'), 'category_id' => 2],
            ['name' => 'Slack', 'logo_url' => $this->getCompanyLogo('slack.com'), 'category_id' => 2],
            ['name' => 'Zoom', 'logo_url' => $this->getCompanyLogo('zoom.us'), 'category_id' => 2],
            ['name' => 'Grammarly', 'logo_url' => $this->getCompanyLogo('grammarly.com'), 'category_id' => 2],
            ['name' => 'Monday.com', 'logo_url' => $this->getCompanyLogo('monday.com'), 'category_id' => 2],
            ['name' => 'Canva', 'logo_url' => $this->getCompanyLogo('canva.com'), 'category_id' => 2],
            ['name' => 'Asana', 'logo_url' => $this->getCompanyLogo('asana.com'), 'category_id' => 2],
            ['name' => 'Trello', 'logo_url' => $this->getCompanyLogo('trello.com'), 'category_id' => 2],
            ['name' => 'ClickUp', 'logo_url' => $this->getCompanyLogo('clickup.com'), 'category_id' => 2],
            ['name' => 'Basecamp', 'logo_url' => $this->getCompanyLogo('basecamp.com'), 'category_id' => 2],
            ['name' => 'Airtable', 'logo_url' => $this->getCompanyLogo('airtable.com'), 'category_id' => 2],
            ['name' => 'Coda', 'logo_url' => $this->getCompanyLogo('coda.io'), 'category_id' => 2],
            ['name' => 'Todoist', 'logo_url' => $this->getCompanyLogo('todoist.com'), 'category_id' => 2],
            ['name' => 'Evernote', 'logo_url' => $this->getCompanyLogo('evernote.com'), 'category_id' => 2],
            ['name' => 'Microsoft 365', 'logo_url' => $this->getCompanyLogo('microsoft.com'), 'category_id' => 2],
            ['name' => 'Google Workspace', 'logo_url' => $this->getCompanyLogo('google.com'), 'category_id' => 2],
            ['name' => 'Miro', 'logo_url' => $this->getCompanyLogo('miro.com'), 'category_id' => 2],
            ['name' => 'Linear', 'logo_url' => $this->getCompanyLogo('linear.app'), 'category_id' => 2],
            ['name' => 'Smartsheet', 'logo_url' => $this->getCompanyLogo('smartsheet.com'), 'category_id' => 2],
            ['name' => 'Wrike', 'logo_url' => $this->getCompanyLogo('wrike.com'), 'category_id' => 2],
            ['name' => 'Loom', 'logo_url' => $this->getCompanyLogo('loom.com'), 'category_id' => 2],
            ['name' => 'Calendly', 'logo_url' => $this->getCompanyLogo('calendly.com'), 'category_id' => 2],
            ['name' => 'Typeform', 'logo_url' => $this->getCompanyLogo('typeform.com'), 'category_id' => 2],
            ['name' => 'Webflow', 'logo_url' => $this->getCompanyLogo('webflow.com'), 'category_id' => 2],
            ['name' => 'Squarespace', 'logo_url' => $this->getCompanyLogo('squarespace.com'), 'category_id' => 2],
            ['name' => 'Ghost', 'logo_url' => $this->getCompanyLogo('ghost.org'), 'category_id' => 2],
            ['name' => 'Beehiiv', 'logo_url' => $this->getCompanyLogo('beehiiv.com'), 'category_id' => 2],
            ['name' => 'HubSpot', 'logo_url' => $this->getCompanyLogo('hubspot.com'), 'category_id' => 2],
            ['name' => 'Pipedrive', 'logo_url' => $this->getCompanyLogo('pipedrive.com'), 'category_id' => 2],
            ['name' => 'Intercom', 'logo_url' => $this->getCompanyLogo('intercom.com'), 'category_id' => 2],
            ['name' => 'Zendesk', 'logo_url' => $this->getCompanyLogo('zendesk.com'), 'category_id' => 2],
            ['name' => 'Mailchimp', 'logo_url' => $this->getCompanyLogo('mailchimp.com'), 'category_id' => 2],
            ['name' => 'ConvertKit', 'logo_url' => $this->getCompanyLogo('convertkit.com'), 'category_id' => 2],
            ['name' => 'Brevo', 'logo_url' => $this->getCompanyLogo('brevo.com'), 'category_id' => 2],
            ['name' => 'Sketch', 'logo_url' => $this->getCompanyLogo('sketch.com'), 'category_id' => 2],
            ['name' => 'InVision', 'logo_url' => $this->getCompanyLogo('invisionapp.com'), 'category_id' => 2],
            ['name' => 'Framer', 'logo_url' => $this->getCompanyLogo('framer.com'), 'category_id' => 2],
            ['name' => 'Obsidian', 'logo_url' => $this->getCompanyLogo('obsidian.md'), 'category_id' => 2],
            ['name' => 'Craft', 'logo_url' => $this->getCompanyLogo('craft.do'), 'category_id' => 2],
            ['name' => 'Ulysses', 'logo_url' => $this->getCompanyLogo('ulysses.app'), 'category_id' => 2],

            // ── Developer Tools (3) ───────────────────────────────────────────────
            ['name' => 'GitHub', 'logo_url' => $this->getCompanyLogo('github.com'), 'category_id' => 3],
            ['name' => 'Vercel', 'logo_url' => $this->getCompanyLogo('vercel.com'), 'category_id' => 3],
            ['name' => 'DigitalOcean', 'logo_url' => $this->getCompanyLogo('digitalocean.com'), 'category_id' => 3],
            ['name' => 'Sentry', 'logo_url' => $this->getCompanyLogo('sentry.io'), 'category_id' => 3],
            ['name' => 'Datadog', 'logo_url' => $this->getCompanyLogo('datadog.com'), 'category_id' => 3],
            ['name' => 'Cloudflare', 'logo_url' => $this->getCompanyLogo('cloudflare.com'), 'category_id' => 3],
            ['name' => 'GitLab', 'logo_url' => $this->getCompanyLogo('gitlab.com'), 'category_id' => 3],
            ['name' => 'Netlify', 'logo_url' => $this->getCompanyLogo('netlify.com'), 'category_id' => 3],
            ['name' => 'Supabase', 'logo_url' => $this->getCompanyLogo('supabase.com'), 'category_id' => 3],
            ['name' => 'PagerDuty', 'logo_url' => $this->getCompanyLogo('pagerduty.com'), 'category_id' => 3],
            ['name' => 'Postman', 'logo_url' => $this->getCompanyLogo('postman.com'), 'category_id' => 3],
            ['name' => 'Atlassian', 'logo_url' => $this->getCompanyLogo('atlassian.com'), 'category_id' => 3],
            ['name' => 'JetBrains', 'logo_url' => $this->getCompanyLogo('jetbrains.com'), 'category_id' => 3],
            ['name' => 'Railway', 'logo_url' => $this->getCompanyLogo('railway.app'), 'category_id' => 3],
            ['name' => 'Render', 'logo_url' => $this->getCompanyLogo('render.com'), 'category_id' => 3],
            ['name' => 'Fly.io', 'logo_url' => $this->getCompanyLogo('fly.io'), 'category_id' => 3],
            ['name' => 'Firebase', 'logo_url' => $this->getCompanyLogo('firebase.google.com'), 'category_id' => 3],
            ['name' => 'PlanetScale', 'logo_url' => $this->getCompanyLogo('planetscale.com'), 'category_id' => 3],
            ['name' => 'MongoDB Atlas', 'logo_url' => $this->getCompanyLogo('mongodb.com'), 'category_id' => 3],
            ['name' => 'Redis Cloud', 'logo_url' => $this->getCompanyLogo('redis.com'), 'category_id' => 3],
            ['name' => 'Elastic Cloud', 'logo_url' => $this->getCompanyLogo('elastic.co'), 'category_id' => 3],
            ['name' => 'Algolia', 'logo_url' => $this->getCompanyLogo('algolia.com'), 'category_id' => 3],
            ['name' => 'CircleCI', 'logo_url' => $this->getCompanyLogo('circleci.com'), 'category_id' => 3],
            ['name' => 'Semaphore CI', 'logo_url' => $this->getCompanyLogo('semaphoreci.com'), 'category_id' => 3],
            ['name' => 'New Relic', 'logo_url' => $this->getCompanyLogo('newrelic.com'), 'category_id' => 3],
            ['name' => 'Dynatrace', 'logo_url' => $this->getCompanyLogo('dynatrace.com'), 'category_id' => 3],
            ['name' => 'Grafana Cloud', 'logo_url' => $this->getCompanyLogo('grafana.com'), 'category_id' => 3],
            ['name' => 'Splunk', 'logo_url' => $this->getCompanyLogo('splunk.com'), 'category_id' => 3],
            ['name' => 'Rollbar', 'logo_url' => $this->getCompanyLogo('rollbar.com'), 'category_id' => 3],
            ['name' => 'LogRocket', 'logo_url' => $this->getCompanyLogo('logrocket.com'), 'category_id' => 3],
            ['name' => 'Hotjar', 'logo_url' => $this->getCompanyLogo('hotjar.com'), 'category_id' => 3],
            ['name' => 'Amplitude', 'logo_url' => $this->getCompanyLogo('amplitude.com'), 'category_id' => 3],
            ['name' => 'Mixpanel', 'logo_url' => $this->getCompanyLogo('mixpanel.com'), 'category_id' => 3],
            ['name' => 'Segment', 'logo_url' => $this->getCompanyLogo('segment.com'), 'category_id' => 3],
            ['name' => 'Stripe', 'logo_url' => $this->getCompanyLogo('stripe.com'), 'category_id' => 3],
            ['name' => 'Twilio', 'logo_url' => $this->getCompanyLogo('twilio.com'), 'category_id' => 3],
            ['name' => 'SendGrid', 'logo_url' => $this->getCompanyLogo('sendgrid.com'), 'category_id' => 3],
            ['name' => 'Mailgun', 'logo_url' => $this->getCompanyLogo('mailgun.com'), 'category_id' => 3],
            ['name' => 'Auth0', 'logo_url' => $this->getCompanyLogo('auth0.com'), 'category_id' => 3],
            ['name' => 'Okta', 'logo_url' => $this->getCompanyLogo('okta.com'), 'category_id' => 3],
            ['name' => 'Snyk', 'logo_url' => $this->getCompanyLogo('snyk.io'), 'category_id' => 3],
            ['name' => 'Retool', 'logo_url' => $this->getCompanyLogo('retool.com'), 'category_id' => 3],
            ['name' => 'Zapier', 'logo_url' => $this->getCompanyLogo('zapier.com'), 'category_id' => 3],
            ['name' => 'Make', 'logo_url' => $this->getCompanyLogo('make.com'), 'category_id' => 3],

            // ── Security (4) ──────────────────────────────────────────────────────
            ['name' => '1Password', 'logo_url' => $this->getCompanyLogo('1password.com'), 'category_id' => 4],
            ['name' => 'LastPass', 'logo_url' => $this->getCompanyLogo('lastpass.com'), 'category_id' => 4],
            ['name' => 'NordVPN', 'logo_url' => $this->getCompanyLogo('nordvpn.com'), 'category_id' => 4],
            ['name' => 'ExpressVPN', 'logo_url' => $this->getCompanyLogo('expressvpn.com'), 'category_id' => 4],
            ['name' => 'Surfshark', 'logo_url' => $this->getCompanyLogo('surfshark.com'), 'category_id' => 4],
            ['name' => 'Bitwarden', 'logo_url' => $this->getCompanyLogo('bitwarden.com'), 'category_id' => 4],
            ['name' => 'Dashlane', 'logo_url' => $this->getCompanyLogo('dashlane.com'), 'category_id' => 4],
            ['name' => 'Malwarebytes', 'logo_url' => $this->getCompanyLogo('malwarebytes.com'), 'category_id' => 4],
            ['name' => 'Norton', 'logo_url' => $this->getCompanyLogo('norton.com'), 'category_id' => 4],
            ['name' => 'Bitdefender', 'logo_url' => $this->getCompanyLogo('bitdefender.com'), 'category_id' => 4],
            ['name' => 'ProtonVPN', 'logo_url' => $this->getCompanyLogo('protonvpn.com'), 'category_id' => 4],
            ['name' => 'Keeper', 'logo_url' => $this->getCompanyLogo('keepersecurity.com'), 'category_id' => 4],
            ['name' => 'RoboForm', 'logo_url' => $this->getCompanyLogo('roboform.com'), 'category_id' => 4],
            ['name' => 'Kaspersky', 'logo_url' => $this->getCompanyLogo('kaspersky.com'), 'category_id' => 4],
            ['name' => 'McAfee', 'logo_url' => $this->getCompanyLogo('mcafee.com'), 'category_id' => 4],
            ['name' => 'ESET', 'logo_url' => $this->getCompanyLogo('eset.com'), 'category_id' => 4],
            ['name' => 'Avast', 'logo_url' => $this->getCompanyLogo('avast.com'), 'category_id' => 4],
            ['name' => 'AVG', 'logo_url' => $this->getCompanyLogo('avg.com'), 'category_id' => 4],
            ['name' => 'Trend Micro', 'logo_url' => $this->getCompanyLogo('trendmicro.com'), 'category_id' => 4],
            ['name' => 'Webroot', 'logo_url' => $this->getCompanyLogo('webroot.com'), 'category_id' => 4],
            ['name' => 'F-Secure', 'logo_url' => $this->getCompanyLogo('f-secure.com'), 'category_id' => 4],
            ['name' => 'Sophos', 'logo_url' => $this->getCompanyLogo('sophos.com'), 'category_id' => 4],
            ['name' => 'CrowdStrike', 'logo_url' => $this->getCompanyLogo('crowdstrike.com'), 'category_id' => 4],
            ['name' => 'SentinelOne', 'logo_url' => $this->getCompanyLogo('sentinelone.com'), 'category_id' => 4],
            ['name' => 'Zscaler', 'logo_url' => $this->getCompanyLogo('zscaler.com'), 'category_id' => 4],
            ['name' => 'Tailscale', 'logo_url' => $this->getCompanyLogo('tailscale.com'), 'category_id' => 4],
            ['name' => 'Mullvad VPN', 'logo_url' => $this->getCompanyLogo('mullvad.net'), 'category_id' => 4],
            ['name' => 'Private Internet Access', 'logo_url' => $this->getCompanyLogo('privateinternetaccess.com'), 'category_id' => 4],
            ['name' => 'CyberGhost', 'logo_url' => $this->getCompanyLogo('cyberghostvpn.com'), 'category_id' => 4],
            ['name' => 'IPVanish', 'logo_url' => $this->getCompanyLogo('ipvanish.com'), 'category_id' => 4],
            ['name' => 'Proton Mail', 'logo_url' => $this->getCompanyLogo('proton.me'), 'category_id' => 4],
            ['name' => 'Mimecast', 'logo_url' => $this->getCompanyLogo('mimecast.com'), 'category_id' => 4],
            ['name' => 'Proofpoint', 'logo_url' => $this->getCompanyLogo('proofpoint.com'), 'category_id' => 4],
            ['name' => 'KnowBe4', 'logo_url' => $this->getCompanyLogo('knowbe4.com'), 'category_id' => 4],
            ['name' => 'Qualys', 'logo_url' => $this->getCompanyLogo('qualys.com'), 'category_id' => 4],
            ['name' => 'Rapid7', 'logo_url' => $this->getCompanyLogo('rapid7.com'), 'category_id' => 4],
            ['name' => 'Tenable', 'logo_url' => $this->getCompanyLogo('tenable.com'), 'category_id' => 4],
            ['name' => 'HackerOne', 'logo_url' => $this->getCompanyLogo('hackerone.com'), 'category_id' => 4],
            ['name' => 'Bugcrowd', 'logo_url' => $this->getCompanyLogo('bugcrowd.com'), 'category_id' => 4],
            ['name' => 'Acronis', 'logo_url' => $this->getCompanyLogo('acronis.com'), 'category_id' => 4],
            ['name' => 'Veeam', 'logo_url' => $this->getCompanyLogo('veeam.com'), 'category_id' => 4],
            ['name' => 'Varonis', 'logo_url' => $this->getCompanyLogo('varonis.com'), 'category_id' => 4],
            ['name' => 'Imperva', 'logo_url' => $this->getCompanyLogo('imperva.com'), 'category_id' => 4],

            // ── Education (5) ─────────────────────────────────────────────────────
            ['name' => 'Duolingo', 'logo_url' => $this->getCompanyLogo('duolingo.com'), 'category_id' => 5],
            ['name' => 'Coursera', 'logo_url' => $this->getCompanyLogo('coursera.org'), 'category_id' => 5],
            ['name' => 'Skillshare', 'logo_url' => $this->getCompanyLogo('skillshare.com'), 'category_id' => 5],
            ['name' => 'MasterClass', 'logo_url' => $this->getCompanyLogo('masterclass.com'), 'category_id' => 5],
            ['name' => 'Brilliant', 'logo_url' => $this->getCompanyLogo('brilliant.org'), 'category_id' => 5],
            ['name' => 'Udemy', 'logo_url' => $this->getCompanyLogo('udemy.com'), 'category_id' => 5],
            ['name' => 'LinkedIn Learning', 'logo_url' => $this->getCompanyLogo('linkedin.com'), 'category_id' => 5],
            ['name' => 'Pluralsight', 'logo_url' => $this->getCompanyLogo('pluralsight.com'), 'category_id' => 5],
            ['name' => 'Babbel', 'logo_url' => $this->getCompanyLogo('babbel.com'), 'category_id' => 5],
            ['name' => 'Codecademy', 'logo_url' => $this->getCompanyLogo('codecademy.com'), 'category_id' => 5],
            ['name' => 'Frontend Masters', 'logo_url' => $this->getCompanyLogo('frontendmasters.com'), 'category_id' => 5],
            ['name' => 'edX', 'logo_url' => $this->getCompanyLogo('edx.org'), 'category_id' => 5],
            ['name' => 'DataCamp', 'logo_url' => $this->getCompanyLogo('datacamp.com'), 'category_id' => 5],
            ['name' => 'Udacity', 'logo_url' => $this->getCompanyLogo('udacity.com'), 'category_id' => 5],
            ['name' => 'Rosetta Stone', 'logo_url' => $this->getCompanyLogo('rosettastone.com'), 'category_id' => 5],
            ['name' => 'Busuu', 'logo_url' => $this->getCompanyLogo('busuu.com'), 'category_id' => 5],
            ['name' => 'italki', 'logo_url' => $this->getCompanyLogo('italki.com'), 'category_id' => 5],
            ['name' => 'Preply', 'logo_url' => $this->getCompanyLogo('preply.com'), 'category_id' => 5],
            ['name' => 'Chegg', 'logo_url' => $this->getCompanyLogo('chegg.com'), 'category_id' => 5],
            ['name' => 'Quizlet', 'logo_url' => $this->getCompanyLogo('quizlet.com'), 'category_id' => 5],
            ['name' => 'Wolfram Alpha', 'logo_url' => $this->getCompanyLogo('wolframalpha.com'), 'category_id' => 5],
            ['name' => 'Yousician', 'logo_url' => $this->getCompanyLogo('yousician.com'), 'category_id' => 5],
            ['name' => 'Flowkey', 'logo_url' => $this->getCompanyLogo('flowkey.com'), 'category_id' => 5],
            ['name' => 'Guitar Tricks', 'logo_url' => $this->getCompanyLogo('guitartricks.com'), 'category_id' => 5],
            ['name' => "O'Reilly", 'logo_url' => $this->getCompanyLogo('oreilly.com'), 'category_id' => 5],
            ['name' => 'A Cloud Guru', 'logo_url' => $this->getCompanyLogo('acloudguru.com'), 'category_id' => 5],
            ['name' => 'SANS Institute', 'logo_url' => $this->getCompanyLogo('sans.org'), 'category_id' => 5],
            ['name' => 'EC-Council', 'logo_url' => $this->getCompanyLogo('eccouncil.org'), 'category_id' => 5],
            ['name' => 'AlgoExpert', 'logo_url' => $this->getCompanyLogo('algoexpert.io'), 'category_id' => 5],
            ['name' => 'LeetCode Premium', 'logo_url' => $this->getCompanyLogo('leetcode.com'), 'category_id' => 5],
            ['name' => 'Educative', 'logo_url' => $this->getCompanyLogo('educative.io'), 'category_id' => 5],
            ['name' => 'Egghead', 'logo_url' => $this->getCompanyLogo('egghead.io'), 'category_id' => 5],
            ['name' => 'Scrimba', 'logo_url' => $this->getCompanyLogo('scrimba.com'), 'category_id' => 5],
            ['name' => 'Springboard', 'logo_url' => $this->getCompanyLogo('springboard.com'), 'category_id' => 5],
            ['name' => 'Magoosh', 'logo_url' => $this->getCompanyLogo('magoosh.com'), 'category_id' => 5],
            ['name' => 'IXL Learning', 'logo_url' => $this->getCompanyLogo('ixl.com'), 'category_id' => 5],
            ['name' => 'TalentLMS', 'logo_url' => $this->getCompanyLogo('talentlms.com'), 'category_id' => 5],
            ['name' => 'Docebo', 'logo_url' => $this->getCompanyLogo('docebo.com'), 'category_id' => 5],
            ['name' => 'Domestika', 'logo_url' => $this->getCompanyLogo('domestika.org'), 'category_id' => 5],
            ['name' => 'CreativeLive', 'logo_url' => $this->getCompanyLogo('creativelive.com'), 'category_id' => 5],
            ['name' => 'Pimsleur', 'logo_url' => $this->getCompanyLogo('pimsleur.com'), 'category_id' => 5],
            ['name' => 'Lingoda', 'logo_url' => $this->getCompanyLogo('lingoda.com'), 'category_id' => 5],
            ['name' => 'LingQ', 'logo_url' => $this->getCompanyLogo('lingq.com'), 'category_id' => 5],
            ['name' => 'Varsity Tutors', 'logo_url' => $this->getCompanyLogo('varsitytutors.com'), 'category_id' => 5],

            // ── Health (6) ────────────────────────────────────────────────────────
            ['name' => 'Headspace', 'logo_url' => $this->getCompanyLogo('headspace.com'), 'category_id' => 6],
            ['name' => 'Calm', 'logo_url' => $this->getCompanyLogo('calm.com'), 'category_id' => 6],
            ['name' => 'Noom', 'logo_url' => $this->getCompanyLogo('noom.com'), 'category_id' => 6],
            ['name' => 'MyFitnessPal', 'logo_url' => $this->getCompanyLogo('myfitnesspal.com'), 'category_id' => 6],
            ['name' => 'Peloton', 'logo_url' => $this->getCompanyLogo('peloton.com'), 'category_id' => 6],
            ['name' => 'Strava', 'logo_url' => $this->getCompanyLogo('strava.com'), 'category_id' => 6],
            ['name' => 'BetterHelp', 'logo_url' => $this->getCompanyLogo('betterhelp.com'), 'category_id' => 6],
            ['name' => 'Talkspace', 'logo_url' => $this->getCompanyLogo('talkspace.com'), 'category_id' => 6],
            ['name' => 'Zwift', 'logo_url' => $this->getCompanyLogo('zwift.com'), 'category_id' => 6],
            ['name' => 'ClassPass', 'logo_url' => $this->getCompanyLogo('classpass.com'), 'category_id' => 6],
            ['name' => 'Teladoc', 'logo_url' => $this->getCompanyLogo('teladoc.com'), 'category_id' => 6],
            ['name' => 'Fitbit Premium', 'logo_url' => $this->getCompanyLogo('fitbit.com'), 'category_id' => 6],
            ['name' => 'WHOOP', 'logo_url' => $this->getCompanyLogo('whoop.com'), 'category_id' => 6],
            ['name' => 'Oura', 'logo_url' => $this->getCompanyLogo('ouraring.com'), 'category_id' => 6],
            ['name' => 'Freeletics', 'logo_url' => $this->getCompanyLogo('freeletics.com'), 'category_id' => 6],
            ['name' => 'Centr', 'logo_url' => $this->getCompanyLogo('centr.com'), 'category_id' => 6],
            ['name' => 'Alo Moves', 'logo_url' => $this->getCompanyLogo('alomoves.com'), 'category_id' => 6],
            ['name' => 'Glo Yoga', 'logo_url' => $this->getCompanyLogo('glo.com'), 'category_id' => 6],
            ['name' => 'Ten Percent Happier', 'logo_url' => $this->getCompanyLogo('tenpercent.com'), 'category_id' => 6],
            ['name' => 'Waking Up', 'logo_url' => $this->getCompanyLogo('wakingup.com'), 'category_id' => 6],
            ['name' => 'Aura', 'logo_url' => $this->getCompanyLogo('aurahealth.io'), 'category_id' => 6],
            ['name' => 'Cerebral', 'logo_url' => $this->getCompanyLogo('cerebral.com'), 'category_id' => 6],
            ['name' => 'Hims', 'logo_url' => $this->getCompanyLogo('forhims.com'), 'category_id' => 6],
            ['name' => 'Hers', 'logo_url' => $this->getCompanyLogo('forhers.com'), 'category_id' => 6],
            ['name' => 'Ro', 'logo_url' => $this->getCompanyLogo('ro.co'), 'category_id' => 6],
            ['name' => 'MDLive', 'logo_url' => $this->getCompanyLogo('mdlive.com'), 'category_id' => 6],
            ['name' => 'Amwell', 'logo_url' => $this->getCompanyLogo('amwell.com'), 'category_id' => 6],
            ['name' => 'PlushCare', 'logo_url' => $this->getCompanyLogo('plushcare.com'), 'category_id' => 6],
            ['name' => 'One Medical', 'logo_url' => $this->getCompanyLogo('onemedical.com'), 'category_id' => 6],
            ['name' => 'Daily Harvest', 'logo_url' => $this->getCompanyLogo('daily-harvest.com'), 'category_id' => 6],
            ['name' => 'Factor', 'logo_url' => $this->getCompanyLogo('factor75.com'), 'category_id' => 6],
            ['name' => 'Trifecta Nutrition', 'logo_url' => $this->getCompanyLogo('trifectanutrition.com'), 'category_id' => 6],
            ['name' => 'Lose It!', 'logo_url' => $this->getCompanyLogo('loseit.com'), 'category_id' => 6],
            ['name' => 'Lifesum', 'logo_url' => $this->getCompanyLogo('lifesum.com'), 'category_id' => 6],
            ['name' => 'Rise Science', 'logo_url' => $this->getCompanyLogo('risescience.com'), 'category_id' => 6],
            ['name' => 'Levels Health', 'logo_url' => $this->getCompanyLogo('levelshealth.com'), 'category_id' => 6],
            ['name' => 'Nutrisense', 'logo_url' => $this->getCompanyLogo('nutrisense.io'), 'category_id' => 6],
            ['name' => 'Sleep Cycle', 'logo_url' => $this->getCompanyLogo('sleepcycle.com'), 'category_id' => 6],
            ['name' => 'Endel', 'logo_url' => $this->getCompanyLogo('endel.io'), 'category_id' => 6],
            ['name' => 'Brain.fm', 'logo_url' => $this->getCompanyLogo('brain.fm'), 'category_id' => 6],
            ['name' => 'Happify', 'logo_url' => $this->getCompanyLogo('happify.com'), 'category_id' => 6],
            ['name' => 'TrainerRoad', 'logo_url' => $this->getCompanyLogo('trainerroad.com'), 'category_id' => 6],
            ['name' => 'Wahoo SYSTM', 'logo_url' => $this->getCompanyLogo('wahoofitness.com'), 'category_id' => 6],
            ['name' => 'Les Mills+', 'logo_url' => $this->getCompanyLogo('lesmills.com'), 'category_id' => 6],
            ['name' => 'Supernatural', 'logo_url' => $this->getCompanyLogo('getsupernatural.com'), 'category_id' => 6],

            // ── News (7) ──────────────────────────────────────────────────────────
            ['name' => 'New York Times', 'logo_url' => $this->getCompanyLogo('nytimes.com'), 'category_id' => 7],
            ['name' => 'Wall Street Journal', 'logo_url' => $this->getCompanyLogo('wsj.com'), 'category_id' => 7],
            ['name' => 'The Economist', 'logo_url' => $this->getCompanyLogo('economist.com'), 'category_id' => 7],
            ['name' => 'Financial Times', 'logo_url' => $this->getCompanyLogo('ft.com'), 'category_id' => 7],
            ['name' => 'Washington Post', 'logo_url' => $this->getCompanyLogo('washingtonpost.com'), 'category_id' => 7],
            ['name' => 'Bloomberg', 'logo_url' => $this->getCompanyLogo('bloomberg.com'), 'category_id' => 7],
            ['name' => 'The Atlantic', 'logo_url' => $this->getCompanyLogo('theatlantic.com'), 'category_id' => 7],
            ['name' => 'Wired', 'logo_url' => $this->getCompanyLogo('wired.com'), 'category_id' => 7],
            ['name' => 'Medium', 'logo_url' => $this->getCompanyLogo('medium.com'), 'category_id' => 7],
            ['name' => 'The New Yorker', 'logo_url' => $this->getCompanyLogo('newyorker.com'), 'category_id' => 7],
            ['name' => 'MIT Technology Review', 'logo_url' => $this->getCompanyLogo('technologyreview.com'), 'category_id' => 7],
            ['name' => 'Harvard Business Review', 'logo_url' => $this->getCompanyLogo('hbr.org'), 'category_id' => 7],
            ['name' => 'National Geographic', 'logo_url' => $this->getCompanyLogo('nationalgeographic.com'), 'category_id' => 7],
            ['name' => 'Scientific American', 'logo_url' => $this->getCompanyLogo('scientificamerican.com'), 'category_id' => 7],
            ['name' => 'New Scientist', 'logo_url' => $this->getCompanyLogo('newscientist.com'), 'category_id' => 7],
            ['name' => 'The Guardian', 'logo_url' => $this->getCompanyLogo('theguardian.com'), 'category_id' => 7],
            ['name' => 'Foreign Affairs', 'logo_url' => $this->getCompanyLogo('foreignaffairs.com'), 'category_id' => 7],
            ['name' => 'Foreign Policy', 'logo_url' => $this->getCompanyLogo('foreignpolicy.com'), 'category_id' => 7],
            ['name' => 'The Information', 'logo_url' => $this->getCompanyLogo('theinformation.com'), 'category_id' => 7],
            ['name' => 'Stratechery', 'logo_url' => $this->getCompanyLogo('stratechery.com'), 'category_id' => 7],
            ['name' => 'Morning Brew', 'logo_url' => $this->getCompanyLogo('morningbrew.com'), 'category_id' => 7],
            ['name' => 'Puck', 'logo_url' => $this->getCompanyLogo('puck.news'), 'category_id' => 7],
            ['name' => 'The Free Press', 'logo_url' => $this->getCompanyLogo('thefp.com'), 'category_id' => 7],
            ['name' => 'Rolling Stone', 'logo_url' => $this->getCompanyLogo('rollingstone.com'), 'category_id' => 7],
            ['name' => 'Vanity Fair', 'logo_url' => $this->getCompanyLogo('vanityfair.com'), 'category_id' => 7],
            ['name' => 'Variety', 'logo_url' => $this->getCompanyLogo('variety.com'), 'category_id' => 7],
            ['name' => 'Hollywood Reporter', 'logo_url' => $this->getCompanyLogo('hollywoodreporter.com'), 'category_id' => 7],
            ['name' => 'Pitchfork', 'logo_url' => $this->getCompanyLogo('pitchfork.com'), 'category_id' => 7],
            ['name' => 'Billboard', 'logo_url' => $this->getCompanyLogo('billboard.com'), 'category_id' => 7],
            ['name' => 'Nature', 'logo_url' => $this->getCompanyLogo('nature.com'), 'category_id' => 7],
            ['name' => 'JSTOR', 'logo_url' => $this->getCompanyLogo('jstor.org'), 'category_id' => 7],
            ['name' => 'Springer', 'logo_url' => $this->getCompanyLogo('springer.com'), 'category_id' => 7],
            ['name' => 'Elsevier', 'logo_url' => $this->getCompanyLogo('elsevier.com'), 'category_id' => 7],
            ['name' => "Harper's Magazine", 'logo_url' => $this->getCompanyLogo('harpers.org'), 'category_id' => 7],
            ['name' => 'Publishers Weekly', 'logo_url' => $this->getCompanyLogo('publishersweekly.com'), 'category_id' => 7],
            ['name' => 'VentureBeat', 'logo_url' => $this->getCompanyLogo('venturebeat.com'), 'category_id' => 7],
            ['name' => 'ZDNet', 'logo_url' => $this->getCompanyLogo('zdnet.com'), 'category_id' => 7],
            ['name' => 'IMDb Pro', 'logo_url' => $this->getCompanyLogo('imdb.com'), 'category_id' => 7],
            ['name' => 'Deadline', 'logo_url' => $this->getCompanyLogo('deadline.com'), 'category_id' => 7],
            ['name' => 'Paste Magazine', 'logo_url' => $this->getCompanyLogo('pastemagazine.com'), 'category_id' => 7],
            ['name' => 'Fangoria', 'logo_url' => $this->getCompanyLogo('fangoria.com'), 'category_id' => 7],
            ['name' => 'IndieWire', 'logo_url' => $this->getCompanyLogo('indiewire.com'), 'category_id' => 7],
            ['name' => 'Sight & Sound', 'logo_url' => $this->getCompanyLogo('bfi.org.uk'), 'category_id' => 7],

            // ── Finance (8) ───────────────────────────────────────────────────────
            ['name' => 'YNAB', 'logo_url' => $this->getCompanyLogo('ynab.com'), 'category_id' => 8],
            ['name' => 'QuickBooks', 'logo_url' => $this->getCompanyLogo('quickbooks.com'), 'category_id' => 8],
            ['name' => 'FreshBooks', 'logo_url' => $this->getCompanyLogo('freshbooks.com'), 'category_id' => 8],
            ['name' => 'Xero', 'logo_url' => $this->getCompanyLogo('xero.com'), 'category_id' => 8],
            ['name' => 'Wealthfront', 'logo_url' => $this->getCompanyLogo('wealthfront.com'), 'category_id' => 8],
            ['name' => 'Betterment', 'logo_url' => $this->getCompanyLogo('betterment.com'), 'category_id' => 8],
            ['name' => 'Expensify', 'logo_url' => $this->getCompanyLogo('expensify.com'), 'category_id' => 8],
            ['name' => 'Gusto', 'logo_url' => $this->getCompanyLogo('gusto.com'), 'category_id' => 8],
            ['name' => 'Revolut', 'logo_url' => $this->getCompanyLogo('revolut.com'), 'category_id' => 8],
            ['name' => 'Wise', 'logo_url' => $this->getCompanyLogo('wise.com'), 'category_id' => 8],
            ['name' => 'Monarch Money', 'logo_url' => $this->getCompanyLogo('monarchmoney.com'), 'category_id' => 8],
            ['name' => 'FreeAgent', 'logo_url' => $this->getCompanyLogo('freeagent.com'), 'category_id' => 8],
            ['name' => 'Bench', 'logo_url' => $this->getCompanyLogo('bench.co'), 'category_id' => 8],
            ['name' => 'Sage Business Cloud', 'logo_url' => $this->getCompanyLogo('sage.com'), 'category_id' => 8],
            ['name' => 'Tiller Money', 'logo_url' => $this->getCompanyLogo('tillerhq.com'), 'category_id' => 8],
            ['name' => 'Copilot Money', 'logo_url' => $this->getCompanyLogo('copilot.money'), 'category_id' => 8],
            ['name' => 'Cleo', 'logo_url' => $this->getCompanyLogo('meetcleo.com'), 'category_id' => 8],
            ['name' => 'Albert', 'logo_url' => $this->getCompanyLogo('albert.com'), 'category_id' => 8],
            ['name' => 'SoFi', 'logo_url' => $this->getCompanyLogo('sofi.com'), 'category_id' => 8],
            ['name' => 'Acorns', 'logo_url' => $this->getCompanyLogo('acorns.com'), 'category_id' => 8],
            ['name' => 'Robinhood Gold', 'logo_url' => $this->getCompanyLogo('robinhood.com'), 'category_id' => 8],
            ['name' => 'eToro', 'logo_url' => $this->getCompanyLogo('etoro.com'), 'category_id' => 8],
            ['name' => 'M1 Finance', 'logo_url' => $this->getCompanyLogo('m1.com'), 'category_id' => 8],
            ['name' => 'Trading 212', 'logo_url' => $this->getCompanyLogo('trading212.com'), 'category_id' => 8],
            ['name' => 'Remitly', 'logo_url' => $this->getCompanyLogo('remitly.com'), 'category_id' => 8],
            ['name' => 'Payoneer', 'logo_url' => $this->getCompanyLogo('payoneer.com'), 'category_id' => 8],
            ['name' => 'Chime', 'logo_url' => $this->getCompanyLogo('chime.com'), 'category_id' => 8],
            ['name' => 'Dave', 'logo_url' => $this->getCompanyLogo('dave.com'), 'category_id' => 8],
            ['name' => 'MoneyLion', 'logo_url' => $this->getCompanyLogo('moneylion.com'), 'category_id' => 8],
            ['name' => 'Deel', 'logo_url' => $this->getCompanyLogo('deel.com'), 'category_id' => 8],
            ['name' => 'Remote', 'logo_url' => $this->getCompanyLogo('remote.com'), 'category_id' => 8],
            ['name' => 'BambooHR', 'logo_url' => $this->getCompanyLogo('bamboohr.com'), 'category_id' => 8],
            ['name' => 'Rippling', 'logo_url' => $this->getCompanyLogo('rippling.com'), 'category_id' => 8],
            ['name' => 'Ramp', 'logo_url' => $this->getCompanyLogo('ramp.com'), 'category_id' => 8],
            ['name' => 'Brex', 'logo_url' => $this->getCompanyLogo('brex.com'), 'category_id' => 8],
            ['name' => 'Spendesk', 'logo_url' => $this->getCompanyLogo('spendesk.com'), 'category_id' => 8],
            ['name' => 'Pleo', 'logo_url' => $this->getCompanyLogo('pleo.io'), 'category_id' => 8],
            ['name' => 'TravelPerk', 'logo_url' => $this->getCompanyLogo('travelperk.com'), 'category_id' => 8],
            ['name' => 'Mercury', 'logo_url' => $this->getCompanyLogo('mercury.com'), 'category_id' => 8],
            ['name' => 'Lemonade Insurance', 'logo_url' => $this->getCompanyLogo('lemonade.com'), 'category_id' => 8],
            ['name' => 'Rocket Money', 'logo_url' => $this->getCompanyLogo('rocketmoney.com'), 'category_id' => 8],
            ['name' => 'myFICO', 'logo_url' => $this->getCompanyLogo('myfico.com'), 'category_id' => 8],
            ['name' => 'LifeLock', 'logo_url' => $this->getCompanyLogo('lifelock.com'), 'category_id' => 8],
            ['name' => 'Fundbox', 'logo_url' => $this->getCompanyLogo('fundbox.com'), 'category_id' => 8],

            // ── Gaming (9) ────────────────────────────────────────────────────────
            ['name' => 'Xbox Game Pass', 'logo_url' => $this->getCompanyLogo('xbox.com'), 'category_id' => 9],
            ['name' => 'PlayStation Plus', 'logo_url' => $this->getCompanyLogo('playstation.com'), 'category_id' => 9],
            ['name' => 'EA Play', 'logo_url' => $this->getCompanyLogo('ea.com'), 'category_id' => 9],
            ['name' => 'Nintendo Switch Online', 'logo_url' => $this->getCompanyLogo('nintendo.com'), 'category_id' => 9],
            ['name' => 'Ubisoft+', 'logo_url' => $this->getCompanyLogo('ubisoft.com'), 'category_id' => 9],
            ['name' => 'Apple Arcade', 'logo_url' => $this->getCompanyLogo('apple.com'), 'category_id' => 9],
            ['name' => 'GeForce Now', 'logo_url' => $this->getCompanyLogo('nvidia.com'), 'category_id' => 9],
            ['name' => 'Humble Bundle', 'logo_url' => $this->getCompanyLogo('humblebundle.com'), 'category_id' => 9],
            ['name' => 'Discord Nitro', 'logo_url' => $this->getCompanyLogo('discord.com'), 'category_id' => 9],
            ['name' => 'D&D Beyond', 'logo_url' => $this->getCompanyLogo('dndbeyond.com'), 'category_id' => 9],
            ['name' => 'Paradox Interactive', 'logo_url' => $this->getCompanyLogo('paradoxinteractive.com'), 'category_id' => 9],
            ['name' => 'Google Play Pass', 'logo_url' => $this->getCompanyLogo('google.com'), 'category_id' => 9],
            ['name' => 'Shadow', 'logo_url' => $this->getCompanyLogo('shadow.tech'), 'category_id' => 9],
            ['name' => 'Blacknut', 'logo_url' => $this->getCompanyLogo('blacknut.com'), 'category_id' => 9],
            ['name' => 'GameFly', 'logo_url' => $this->getCompanyLogo('gamefly.com'), 'category_id' => 9],
            ['name' => 'GOG Galaxy', 'logo_url' => $this->getCompanyLogo('gog.com'), 'category_id' => 9],
            ['name' => 'Epic Games Store', 'logo_url' => $this->getCompanyLogo('epicgames.com'), 'category_id' => 9],
            ['name' => 'Battle.net', 'logo_url' => $this->getCompanyLogo('blizzard.com'), 'category_id' => 9],
            ['name' => 'Bethesda.net', 'logo_url' => $this->getCompanyLogo('bethesda.net'), 'category_id' => 9],
            ['name' => 'Steam', 'logo_url' => $this->getCompanyLogo('steampowered.com'), 'category_id' => 9],
            ['name' => 'Rockstar Games', 'logo_url' => $this->getCompanyLogo('rockstargames.com'), 'category_id' => 9],
            ['name' => 'Capcom', 'logo_url' => $this->getCompanyLogo('capcom.com'), 'category_id' => 9],
            ['name' => 'Sega', 'logo_url' => $this->getCompanyLogo('sega.com'), 'category_id' => 9],
            ['name' => 'CD Projekt Red', 'logo_url' => $this->getCompanyLogo('cdprojekt.com'), 'category_id' => 9],
            ['name' => 'Larian Studios', 'logo_url' => $this->getCompanyLogo('larian.com'), 'category_id' => 9],
            ['name' => 'Roll20', 'logo_url' => $this->getCompanyLogo('roll20.net'), 'category_id' => 9],
            ['name' => 'Fantasy Grounds', 'logo_url' => $this->getCompanyLogo('fantasygrounds.com'), 'category_id' => 9],
            ['name' => 'Tabletopia', 'logo_url' => $this->getCompanyLogo('tabletopia.com'), 'category_id' => 9],
            ['name' => 'Board Game Arena', 'logo_url' => $this->getCompanyLogo('boardgamearena.com'), 'category_id' => 9],
            ['name' => 'Jackbox Games', 'logo_url' => $this->getCompanyLogo('jackboxgames.com'), 'category_id' => 9],
            ['name' => 'Nexus Mods Premium', 'logo_url' => $this->getCompanyLogo('nexusmods.com'), 'category_id' => 9],
            ['name' => 'FACEIT', 'logo_url' => $this->getCompanyLogo('faceit.com'), 'category_id' => 9],
            ['name' => 'Green Man Gaming', 'logo_url' => $this->getCompanyLogo('greenmangaming.com'), 'category_id' => 9],
            ['name' => 'Fanatical', 'logo_url' => $this->getCompanyLogo('fanatical.com'), 'category_id' => 9],
            ['name' => 'Razer Gold', 'logo_url' => $this->getCompanyLogo('razer.com'), 'category_id' => 9],
            ['name' => 'Amazon Luna', 'logo_url' => $this->getCompanyLogo('amazon.com'), 'category_id' => 9],
            ['name' => 'Boosteroid', 'logo_url' => $this->getCompanyLogo('boosteroid.com'), 'category_id' => 9],
            ['name' => 'Overwolf', 'logo_url' => $this->getCompanyLogo('overwolf.com'), 'category_id' => 9],
            ['name' => 'Guilded', 'logo_url' => $this->getCompanyLogo('guilded.gg'), 'category_id' => 9],
            ['name' => 'Demiplane', 'logo_url' => $this->getCompanyLogo('demiplane.com'), 'category_id' => 9],

            // ── Entertainment – additional (1) ───────────────────────────────────
            ['name' => 'Mubi Go', 'logo_url' => $this->getCompanyLogo('mubi.com'), 'category_id' => 1],
            ['name' => 'Midnight Pulp', 'logo_url' => $this->getCompanyLogo('midnightpulp.com'), 'category_id' => 1],
            ['name' => 'Mubi', 'logo_url' => $this->getCompanyLogo('mubi.com'), 'category_id' => 1],
            ['name' => 'Arrow Player', 'logo_url' => $this->getCompanyLogo('arrow-player.com'), 'category_id' => 1],
            ['name' => 'Criterion Channel', 'logo_url' => $this->getCompanyLogo('criterionchannel.com'), 'category_id' => 1],
            ['name' => 'Mhz Choice', 'logo_url' => $this->getCompanyLogo('mhzchoice.com'), 'category_id' => 1],
            ['name' => 'Kino Marquee', 'logo_url' => $this->getCompanyLogo('kinomarquee.com'), 'category_id' => 1],
            ['name' => 'ViX', 'logo_url' => $this->getCompanyLogo('vix.com'), 'category_id' => 1],
            ['name' => 'Tubi', 'logo_url' => $this->getCompanyLogo('tubi.tv'), 'category_id' => 1],
            ['name' => 'Pluto TV', 'logo_url' => $this->getCompanyLogo('pluto.tv'), 'category_id' => 1],
            ['name' => 'Hayu', 'logo_url' => $this->getCompanyLogo('hayu.com'), 'category_id' => 1],
            ['name' => 'Sundance Now', 'logo_url' => $this->getCompanyLogo('sundancenow.com'), 'category_id' => 1],
            ['name' => 'Topic', 'logo_url' => $this->getCompanyLogo('topic.com'), 'category_id' => 1],
            ['name' => 'Fandor', 'logo_url' => $this->getCompanyLogo('fandor.com'), 'category_id' => 1],
            ['name' => 'Magnolia Selects', 'logo_url' => $this->getCompanyLogo('magnoliapictures.com'), 'category_id' => 1],
            ['name' => 'Classix', 'logo_url' => $this->getCompanyLogo('classix.com'), 'category_id' => 1],
            ['name' => 'Retrocrush', 'logo_url' => $this->getCompanyLogo('retrocrush.tv'), 'category_id' => 1],
            ['name' => 'AsianCrush', 'logo_url' => $this->getCompanyLogo('asiancrush.com'), 'category_id' => 1],
            ['name' => 'Viki', 'logo_url' => $this->getCompanyLogo('viki.com'), 'category_id' => 1],
            ['name' => 'Kocowa', 'logo_url' => $this->getCompanyLogo('kocowa.com'), 'category_id' => 1],
            ['name' => 'Viu', 'logo_url' => $this->getCompanyLogo('viu.com'), 'category_id' => 1],
            ['name' => 'WeTV', 'logo_url' => $this->getCompanyLogo('wetv.vip'), 'category_id' => 1],
            ['name' => 'iQIYI', 'logo_url' => $this->getCompanyLogo('iq.com'), 'category_id' => 1],

            // ── Productivity – additional (2) ────────────────────────────────────
            ['name' => 'Notion AI', 'logo_url' => $this->getCompanyLogo('notion.so'), 'category_id' => 2],
            ['name' => 'Taskade', 'logo_url' => $this->getCompanyLogo('taskade.com'), 'category_id' => 2],
            ['name' => 'Hive', 'logo_url' => $this->getCompanyLogo('hive.com'), 'category_id' => 2],
            ['name' => 'Nifty', 'logo_url' => $this->getCompanyLogo('niftypm.com'), 'category_id' => 2],
            ['name' => 'Teamwork', 'logo_url' => $this->getCompanyLogo('teamwork.com'), 'category_id' => 2],
            ['name' => 'Quip', 'logo_url' => $this->getCompanyLogo('quip.com'), 'category_id' => 2],
            ['name' => 'Dropbox Paper', 'logo_url' => $this->getCompanyLogo('dropbox.com'), 'category_id' => 2],
            ['name' => 'Confluence', 'logo_url' => $this->getCompanyLogo('atlassian.com'), 'category_id' => 2],
            ['name' => 'Jira', 'logo_url' => $this->getCompanyLogo('atlassian.com'), 'category_id' => 2],
            ['name' => 'Shortcut', 'logo_url' => $this->getCompanyLogo('shortcut.com'), 'category_id' => 2],
            ['name' => 'Height', 'logo_url' => $this->getCompanyLogo('height.app'), 'category_id' => 2],
            ['name' => 'Plane', 'logo_url' => $this->getCompanyLogo('plane.so'), 'category_id' => 2],
            ['name' => 'Folk CRM', 'logo_url' => $this->getCompanyLogo('folk.app'), 'category_id' => 2],
            ['name' => 'Attio', 'logo_url' => $this->getCompanyLogo('attio.com'), 'category_id' => 2],
            ['name' => 'Descript', 'logo_url' => $this->getCompanyLogo('descript.com'), 'category_id' => 2],
            ['name' => 'Otter.ai', 'logo_url' => $this->getCompanyLogo('otter.ai'), 'category_id' => 2],
            ['name' => 'Fireflies.ai', 'logo_url' => $this->getCompanyLogo('fireflies.ai'), 'category_id' => 2],
            ['name' => 'Grain', 'logo_url' => $this->getCompanyLogo('grain.com'), 'category_id' => 2],
            ['name' => 'Fathom', 'logo_url' => $this->getCompanyLogo('fathom.video'), 'category_id' => 2],
            ['name' => 'Krisp', 'logo_url' => $this->getCompanyLogo('krisp.ai'), 'category_id' => 2],
            ['name' => 'Cleanshot X', 'logo_url' => $this->getCompanyLogo('cleanshot.com'), 'category_id' => 2],
            ['name' => 'Setapp', 'logo_url' => $this->getCompanyLogo('setapp.com'), 'category_id' => 2],
            ['name' => 'Alfred', 'logo_url' => $this->getCompanyLogo('alfredapp.com'), 'category_id' => 2],

            // ── Developer Tools – additional (3) ─────────────────────────────────
            ['name' => 'Bitbucket', 'logo_url' => $this->getCompanyLogo('bitbucket.org'), 'category_id' => 3],
            ['name' => 'Heroku', 'logo_url' => $this->getCompanyLogo('heroku.com'), 'category_id' => 3],
            ['name' => 'AWS', 'logo_url' => $this->getCompanyLogo('aws.amazon.com'), 'category_id' => 3],
            ['name' => 'Google Cloud', 'logo_url' => $this->getCompanyLogo('cloud.google.com'), 'category_id' => 3],
            ['name' => 'Azure', 'logo_url' => $this->getCompanyLogo('azure.microsoft.com'), 'category_id' => 3],
            ['name' => 'Linode', 'logo_url' => $this->getCompanyLogo('linode.com'), 'category_id' => 3],
            ['name' => 'Vultr', 'logo_url' => $this->getCompanyLogo('vultr.com'), 'category_id' => 3],
            ['name' => 'Hetzner', 'logo_url' => $this->getCompanyLogo('hetzner.com'), 'category_id' => 3],
            ['name' => 'Neon', 'logo_url' => $this->getCompanyLogo('neon.tech'), 'category_id' => 3],
            ['name' => 'Turso', 'logo_url' => $this->getCompanyLogo('turso.tech'), 'category_id' => 3],
            ['name' => 'Xata', 'logo_url' => $this->getCompanyLogo('xata.io'), 'category_id' => 3],
            ['name' => 'Upstash', 'logo_url' => $this->getCompanyLogo('upstash.com'), 'category_id' => 3],
            ['name' => 'Convoy', 'logo_url' => $this->getCompanyLogo('getconvoy.io'), 'category_id' => 3],
            ['name' => 'Hookdeck', 'logo_url' => $this->getCompanyLogo('hookdeck.com'), 'category_id' => 3],
            ['name' => 'Inngest', 'logo_url' => $this->getCompanyLogo('inngest.com'), 'category_id' => 3],
            ['name' => 'Temporal', 'logo_url' => $this->getCompanyLogo('temporal.io'), 'category_id' => 3],
            ['name' => 'LaunchDarkly', 'logo_url' => $this->getCompanyLogo('launchdarkly.com'), 'category_id' => 3],
            ['name' => 'Split.io', 'logo_url' => $this->getCompanyLogo('split.io'), 'category_id' => 3],
            ['name' => 'Statsig', 'logo_url' => $this->getCompanyLogo('statsig.com'), 'category_id' => 3],
            ['name' => 'Flagsmith', 'logo_url' => $this->getCompanyLogo('flagsmith.com'), 'category_id' => 3],
            ['name' => 'Doppler', 'logo_url' => $this->getCompanyLogo('doppler.com'), 'category_id' => 3],
            ['name' => 'Infisical', 'logo_url' => $this->getCompanyLogo('infisical.com'), 'category_id' => 3],
            ['name' => 'n8n', 'logo_url' => $this->getCompanyLogo('n8n.io'), 'category_id' => 3],
            ['name' => 'Pipedream', 'logo_url' => $this->getCompanyLogo('pipedream.com'), 'category_id' => 3],

            // ── Security – additional (4) ─────────────────────────────────────────
            ['name' => 'Huntress', 'logo_url' => $this->getCompanyLogo('huntress.com'), 'category_id' => 4],
            ['name' => 'Red Canary', 'logo_url' => $this->getCompanyLogo('redcanary.com'), 'category_id' => 4],
            ['name' => 'Lacework', 'logo_url' => $this->getCompanyLogo('lacework.com'), 'category_id' => 4],
            ['name' => 'Orca Security', 'logo_url' => $this->getCompanyLogo('orca.security'), 'category_id' => 4],
            ['name' => 'Wiz', 'logo_url' => $this->getCompanyLogo('wiz.io'), 'category_id' => 4],
            ['name' => 'Prisma Cloud', 'logo_url' => $this->getCompanyLogo('paloaltonetworks.com'), 'category_id' => 4],
            ['name' => 'Aqua Security', 'logo_url' => $this->getCompanyLogo('aquasec.com'), 'category_id' => 4],
            ['name' => 'Checkmarx', 'logo_url' => $this->getCompanyLogo('checkmarx.com'), 'category_id' => 4],
            ['name' => 'Veracode', 'logo_url' => $this->getCompanyLogo('veracode.com'), 'category_id' => 4],
            ['name' => 'GitGuardian', 'logo_url' => $this->getCompanyLogo('gitguardian.com'), 'category_id' => 4],
            ['name' => 'Socket', 'logo_url' => $this->getCompanyLogo('socket.dev'), 'category_id' => 4],
            ['name' => 'Jit', 'logo_url' => $this->getCompanyLogo('jit.io'), 'category_id' => 4],
            ['name' => 'Aikido Security', 'logo_url' => $this->getCompanyLogo('aikido.dev'), 'category_id' => 4],
            ['name' => 'Drata', 'logo_url' => $this->getCompanyLogo('drata.com'), 'category_id' => 4],
            ['name' => 'Vanta', 'logo_url' => $this->getCompanyLogo('vanta.com'), 'category_id' => 4],
            ['name' => 'Secureframe', 'logo_url' => $this->getCompanyLogo('secureframe.com'), 'category_id' => 4],
            ['name' => 'Tugboat Logic', 'logo_url' => $this->getCompanyLogo('tugboatlogic.com'), 'category_id' => 4],
            ['name' => 'Persona', 'logo_url' => $this->getCompanyLogo('withpersona.com'), 'category_id' => 4],
            ['name' => 'Jumio', 'logo_url' => $this->getCompanyLogo('jumio.com'), 'category_id' => 4],
            ['name' => 'Onfido', 'logo_url' => $this->getCompanyLogo('onfido.com'), 'category_id' => 4],
            ['name' => 'Authy', 'logo_url' => $this->getCompanyLogo('authy.com'), 'category_id' => 4],
            ['name' => 'Duo Security', 'logo_url' => $this->getCompanyLogo('duo.com'), 'category_id' => 4],
            ['name' => 'Yubico', 'logo_url' => $this->getCompanyLogo('yubico.com'), 'category_id' => 4],

            // ── Education – additional (5) ────────────────────────────────────────
            ['name' => 'Khan Academy', 'logo_url' => $this->getCompanyLogo('khanacademy.org'), 'category_id' => 5],
            ['name' => 'Mimo', 'logo_url' => $this->getCompanyLogo('getmimo.com'), 'category_id' => 5],
            ['name' => 'SoloLearn', 'logo_url' => $this->getCompanyLogo('sololearn.com'), 'category_id' => 5],
            ['name' => 'Enki', 'logo_url' => $this->getCompanyLogo('enki.com'), 'category_id' => 5],
            ['name' => 'Exercism', 'logo_url' => $this->getCompanyLogo('exercism.org'), 'category_id' => 5],
            ['name' => 'Codewars', 'logo_url' => $this->getCompanyLogo('codewars.com'), 'category_id' => 5],
            ['name' => 'HackerRank', 'logo_url' => $this->getCompanyLogo('hackerrank.com'), 'category_id' => 5],
            ['name' => 'Neetcode', 'logo_url' => $this->getCompanyLogo('neetcode.io'), 'category_id' => 5],
            ['name' => 'Interview Cake', 'logo_url' => $this->getCompanyLogo('interviewcake.com'), 'category_id' => 5],
            ['name' => 'Grokking', 'logo_url' => $this->getCompanyLogo('designgurus.io'), 'category_id' => 5],
            ['name' => 'TestGorilla', 'logo_url' => $this->getCompanyLogo('testgorilla.com'), 'category_id' => 5],
            ['name' => 'Mimo', 'logo_url' => $this->getCompanyLogo('mimo.org'), 'category_id' => 5],
            ['name' => 'Tynker', 'logo_url' => $this->getCompanyLogo('tynker.com'), 'category_id' => 5],
            ['name' => 'Code.org', 'logo_url' => $this->getCompanyLogo('code.org'), 'category_id' => 5],
            ['name' => 'Scratch', 'logo_url' => $this->getCompanyLogo('scratch.mit.edu'), 'category_id' => 5],
            ['name' => 'Prodigy', 'logo_url' => $this->getCompanyLogo('prodigygame.com'), 'category_id' => 5],
            ['name' => 'Outschool', 'logo_url' => $this->getCompanyLogo('outschool.com'), 'category_id' => 5],
            ['name' => 'Wyzant', 'logo_url' => $this->getCompanyLogo('wyzant.com'), 'category_id' => 5],
            ['name' => 'Tutoring.com', 'logo_url' => $this->getCompanyLogo('tutoring.com'), 'category_id' => 5],
            ['name' => 'Cambly', 'logo_url' => $this->getCompanyLogo('cambly.com'), 'category_id' => 5],
            ['name' => 'Clozemaster', 'logo_url' => $this->getCompanyLogo('clozemaster.com'), 'category_id' => 5],
            ['name' => 'Anki', 'logo_url' => $this->getCompanyLogo('apps.ankiweb.net'), 'category_id' => 5],

            // ── Health – additional (6) ───────────────────────────────────────────
            ['name' => 'Headspace for Work', 'logo_url' => $this->getCompanyLogo('headspace.com'), 'category_id' => 6],
            ['name' => 'Spring Health', 'logo_url' => $this->getCompanyLogo('springhealth.com'), 'category_id' => 6],
            ['name' => 'Modern Health', 'logo_url' => $this->getCompanyLogo('modernhealth.com'), 'category_id' => 6],
            ['name' => 'Lyra Health', 'logo_url' => $this->getCompanyLogo('lyrahealth.com'), 'category_id' => 6],
            ['name' => 'Sword Health', 'logo_url' => $this->getCompanyLogo('swordhealth.com'), 'category_id' => 6],
            ['name' => 'Brightline', 'logo_url' => $this->getCompanyLogo('hellobrightline.com'), 'category_id' => 6],
            ['name' => 'Garmin Connect', 'logo_url' => $this->getCompanyLogo('connect.garmin.com'), 'category_id' => 6],
            ['name' => 'Apple Fitness+', 'logo_url' => $this->getCompanyLogo('apple.com'), 'category_id' => 6],
            ['name' => 'Nike Training Club', 'logo_url' => $this->getCompanyLogo('nike.com'), 'category_id' => 6],
            ['name' => 'Beachbody On Demand', 'logo_url' => $this->getCompanyLogo('beachbodyondemand.com'), 'category_id' => 6],
            ['name' => 'Daily Burn', 'logo_url' => $this->getCompanyLogo('dailyburn.com'), 'category_id' => 6],
            ['name' => 'Openfit', 'logo_url' => $this->getCompanyLogo('openfit.com'), 'category_id' => 6],
            ['name' => 'Future', 'logo_url' => $this->getCompanyLogo('future.co'), 'category_id' => 6],
            ['name' => 'Caliber', 'logo_url' => $this->getCompanyLogo('caliberstrong.com'), 'category_id' => 6],
            ['name' => 'Stronger by Science', 'logo_url' => $this->getCompanyLogo('strongerbyscience.com'), 'category_id' => 6],
            ['name' => 'Renaissance Periodization', 'logo_url' => $this->getCompanyLogo('renaissanceperiodization.com'), 'category_id' => 6],
            ['name' => 'MacroFactor', 'logo_url' => $this->getCompanyLogo('macrofactorapp.com'), 'category_id' => 6],
            ['name' => 'Cronometer', 'logo_url' => $this->getCompanyLogo('cronometer.com'), 'category_id' => 6],
            ['name' => 'Zero Fasting', 'logo_url' => $this->getCompanyLogo('zerofasting.com'), 'category_id' => 6],
            ['name' => 'DoFasting', 'logo_url' => $this->getCompanyLogo('dofasting.com'), 'category_id' => 6],
            ['name' => 'Flo', 'logo_url' => $this->getCompanyLogo('flo.health'), 'category_id' => 6],
            ['name' => 'Clue', 'logo_url' => $this->getCompanyLogo('helloclue.com'), 'category_id' => 6],

            // ── News – additional (7) ─────────────────────────────────────────────
            ['name' => 'The Dispatch', 'logo_url' => $this->getCompanyLogo('thedispatch.com'), 'category_id' => 7],
            ['name' => 'Substack', 'logo_url' => $this->getCompanyLogo('substack.com'), 'category_id' => 7],
            ['name' => 'Axios', 'logo_url' => $this->getCompanyLogo('axios.com'), 'category_id' => 7],
            ['name' => 'The Hustle', 'logo_url' => $this->getCompanyLogo('thehustle.co'), 'category_id' => 7],
            ['name' => '1440 Daily Digest', 'logo_url' => $this->getCompanyLogo('join1440.com'), 'category_id' => 7],
            ['name' => 'The Browser', 'logo_url' => $this->getCompanyLogo('thebrowser.com'), 'category_id' => 7],
            ['name' => 'Ground News', 'logo_url' => $this->getCompanyLogo('ground.news'), 'category_id' => 7],
            ['name' => 'AllSides', 'logo_url' => $this->getCompanyLogo('allsides.com'), 'category_id' => 7],
            ['name' => 'Artifact', 'logo_url' => $this->getCompanyLogo('artifact.news'), 'category_id' => 7],
            ['name' => 'Flipboard', 'logo_url' => $this->getCompanyLogo('flipboard.com'), 'category_id' => 7],
            ['name' => 'Feedly', 'logo_url' => $this->getCompanyLogo('feedly.com'), 'category_id' => 7],
            ['name' => 'Inoreader', 'logo_url' => $this->getCompanyLogo('inoreader.com'), 'category_id' => 7],
            ['name' => 'NewsBlur', 'logo_url' => $this->getCompanyLogo('newsblur.com'), 'category_id' => 7],
            ['name' => 'Matter', 'logo_url' => $this->getCompanyLogo('getmatter.com'), 'category_id' => 7],
            ['name' => 'Instapaper', 'logo_url' => $this->getCompanyLogo('instapaper.com'), 'category_id' => 7],
            ['name' => 'Pocket', 'logo_url' => $this->getCompanyLogo('getpocket.com'), 'category_id' => 7],
            ['name' => 'Omnivore', 'logo_url' => $this->getCompanyLogo('omnivore.app'), 'category_id' => 7],
            ['name' => 'Apple News+', 'logo_url' => $this->getCompanyLogo('apple.com'), 'category_id' => 7],
            ['name' => 'Google One', 'logo_url' => $this->getCompanyLogo('one.google.com'), 'category_id' => 7],
            ['name' => 'Ars Technica Pro', 'logo_url' => $this->getCompanyLogo('arstechnica.com'), 'category_id' => 7],
            ['name' => 'The Verge', 'logo_url' => $this->getCompanyLogo('theverge.com'), 'category_id' => 7],
            ['name' => 'TechCrunch', 'logo_url' => $this->getCompanyLogo('techcrunch.com'), 'category_id' => 7],

            // ── Finance – additional (8) ──────────────────────────────────────────
            ['name' => 'Wave', 'logo_url' => $this->getCompanyLogo('waveapps.com'), 'category_id' => 8],
            ['name' => 'Zoho Books', 'logo_url' => $this->getCompanyLogo('zoho.com'), 'category_id' => 8],
            ['name' => 'Honeybook', 'logo_url' => $this->getCompanyLogo('honeybook.com'), 'category_id' => 8],
            ['name' => 'Bonsai', 'logo_url' => $this->getCompanyLogo('hellobonsai.com'), 'category_id' => 8],
            ['name' => 'AND CO', 'logo_url' => $this->getCompanyLogo('and.co'), 'category_id' => 8],
            ['name' => 'Invoice Ninja', 'logo_url' => $this->getCompanyLogo('invoiceninja.com'), 'category_id' => 8],
            ['name' => 'Harvest', 'logo_url' => $this->getCompanyLogo('getharvest.com'), 'category_id' => 8],
            ['name' => 'Toggl Track', 'logo_url' => $this->getCompanyLogo('toggl.com'), 'category_id' => 8],
            ['name' => 'Clockify', 'logo_url' => $this->getCompanyLogo('clockify.me'), 'category_id' => 8],
            ['name' => 'Timely', 'logo_url' => $this->getCompanyLogo('timelyapp.com'), 'category_id' => 8],
            ['name' => 'Bill.com', 'logo_url' => $this->getCompanyLogo('bill.com'), 'category_id' => 8],
            ['name' => 'Tipalti', 'logo_url' => $this->getCompanyLogo('tipalti.com'), 'category_id' => 8],
            ['name' => 'Airwallex', 'logo_url' => $this->getCompanyLogo('airwallex.com'), 'category_id' => 8],
            ['name' => 'Stripe Atlas', 'logo_url' => $this->getCompanyLogo('stripe.com'), 'category_id' => 8],
            ['name' => 'Lili', 'logo_url' => $this->getCompanyLogo('lili.co'), 'category_id' => 8],
            ['name' => 'Found', 'logo_url' => $this->getCompanyLogo('found.com'), 'category_id' => 8],
            ['name' => 'Novo', 'logo_url' => $this->getCompanyLogo('novo.co'), 'category_id' => 8],
            ['name' => 'Relay', 'logo_url' => $this->getCompanyLogo('relayfi.com'), 'category_id' => 8],
            ['name' => 'Kabbage', 'logo_url' => $this->getCompanyLogo('kabbage.com'), 'category_id' => 8],
            ['name' => 'Bluevine', 'logo_url' => $this->getCompanyLogo('bluevine.com'), 'category_id' => 8],

            // ── Gaming – additional (9) ───────────────────────────────────────────
            ['name' => 'Stadia', 'logo_url' => $this->getCompanyLogo('stadia.com'), 'category_id' => 9],
            ['name' => 'Xbox Cloud Gaming', 'logo_url' => $this->getCompanyLogo('xbox.com'), 'category_id' => 9],
            ['name' => 'PlayStation Now', 'logo_url' => $this->getCompanyLogo('playstation.com'), 'category_id' => 9],
            ['name' => 'Twitch', 'logo_url' => $this->getCompanyLogo('twitch.tv'), 'category_id' => 9],
            ['name' => 'Patreon (Gaming)', 'logo_url' => $this->getCompanyLogo('patreon.com'), 'category_id' => 9],
            ['name' => 'Kick', 'logo_url' => $this->getCompanyLogo('kick.com'), 'category_id' => 9],
            ['name' => 'Trovo', 'logo_url' => $this->getCompanyLogo('trovo.live'), 'category_id' => 9],
            ['name' => 'Itch.io', 'logo_url' => $this->getCompanyLogo('itch.io'), 'category_id' => 9],
            ['name' => 'Kartridge', 'logo_url' => $this->getCompanyLogo('kartridge.com'), 'category_id' => 9],
            ['name' => 'Antstream Arcade', 'logo_url' => $this->getCompanyLogo('antstream.com'), 'category_id' => 9],
            ['name' => 'Plex Arcade', 'logo_url' => $this->getCompanyLogo('plex.tv'), 'category_id' => 9],
            ['name' => 'Utomik', 'logo_url' => $this->getCompanyLogo('utomik.com'), 'category_id' => 9],
            ['name' => 'GameTree', 'logo_url' => $this->getCompanyLogo('gametree.me'), 'category_id' => 9],
            ['name' => 'Legionfarm', 'logo_url' => $this->getCompanyLogo('legionfarm.com'), 'category_id' => 9],
            ['name' => 'Blizzard Battle.net', 'logo_url' => $this->getCompanyLogo('blizzard.com'), 'category_id' => 9],
            ['name' => 'Origin', 'logo_url' => $this->getCompanyLogo('origin.com'), 'category_id' => 9],
            ['name' => 'Uplay', 'logo_url' => $this->getCompanyLogo('ubisoft.com'), 'category_id' => 9],
            ['name' => 'Arc Browser', 'logo_url' => $this->getCompanyLogo('arc.net'), 'category_id' => 9],
            ['name' => 'Proton Pass', 'logo_url' => $this->getCompanyLogo('proton.me'), 'category_id' => 9],
            ['name' => 'Playco', 'logo_url' => $this->getCompanyLogo('play.co'), 'category_id' => 9],
            ['name' => 'Skillz', 'logo_url' => $this->getCompanyLogo('skillz.com'), 'category_id' => 9],
            ['name' => 'Nerd Street', 'logo_url' => $this->getCompanyLogo('nerdstreet.com'), 'category_id' => 9],
            ['name' => 'Esportal', 'logo_url' => $this->getCompanyLogo('esportal.com'), 'category_id' => 9],
            ['name' => 'Battlefy', 'logo_url' => $this->getCompanyLogo('battlefy.com'), 'category_id' => 9],
            ['name' => 'Toornament', 'logo_url' => $this->getCompanyLogo('toornament.com'), 'category_id' => 9],
            ['name' => 'Challengermode', 'logo_url' => $this->getCompanyLogo('challengermode.com'), 'category_id' => 9],
            ['name' => 'GRID Esports', 'logo_url' => $this->getCompanyLogo('grid.gg'), 'category_id' => 9],
        ])
            ->unique('name')
            ->map(fn($company) => [...$company, 'created_at' => $now, 'updated_at' => $now])
            ->all();

        foreach (array_chunk($companies, 100) as $chunk) {
            Company::query()->upsert($chunk, ['name'], ['logo_url', 'category_id', 'created_at', 'updated_at']);
        }
    }

    private function getCompanyLogo(string $domain): string
    {
        $token = config('services.logodev.publishable_key');

        return "https://img.logo.dev/$domain?token=$token";
    }
}
